# This workflow will build a .NET project

name: Build check

on:
  pull_request:

jobs:
  test:
    name: Build check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore packages for solution
      run: dotnet restore

    - name: Build solution (NET Core)
      run: dotnet build --no-restore -c debug

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 4.7.2

    - name: Build solution (NET Framework)
      run: msbuild YourSolution.sln /p:Configuration=Debug

# Uncomment these lines if you want to run tests
#    - name: Run tests (NET Core)
#      run: dotnet test --no-build -c debug

#    - name: Run tests (NET Framework)
#      run: vstest.console.exe YourTestProject.dll
